# Generated by Django 4.2.30 on 2026-07-29 13:32

import datetime
from decimal import Decimal
import hashlib
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

MIGRATION_SOURCE = "mlcc_migration_0007"


def _program_id(stage, key):
    # The legacy phase-3B grouping key represented one executable program even
    # when several recipe versions referenced it. Preserve that grouping.
    raw = f"{stage}:{key}"
    if len(raw) <= 200:
        return raw
    digest = hashlib.sha256(raw.encode("utf-8")).hexdigest()
    return f"{stage}:{digest}"


def link_legacy_programs(apps, schema_editor):
    Program = apps.get_model("mlcc", "MlccFurnaceProgram")
    Recipe = apps.get_model("mlcc", "MlccRecipe")
    FurnaceLoad = apps.get_model("mlcc", "MlccFurnaceLoad")
    database = schema_editor.connection.alias
    recipes = (
        Recipe.objects.using(database)
        .exclude(furnace_program_key__isnull=True)
        .exclude(furnace_program_key="")
        .order_by("process_stage", "furnace_program_key", "version", "id")
    )
    for recipe in recipes:
        parameters = recipe.parameters if isinstance(recipe.parameters, dict) else {}
        identifier = _program_id(
            recipe.process_stage,
            recipe.furnace_program_key,
        )
        Program.objects.using(database).get_or_create(
            id=identifier,
            defaults={
                "program_key": recipe.furnace_program_key,
                "version": "LEGACY",
                "process_stage": recipe.process_stage,
                "atmosphere_key": parameters.get("atmosphere_key", "legacy"),
                "required_pre_state_key": parameters.get(
                    "required_pre_state_key", "legacy_idle"
                ),
                "resulting_post_state_key": parameters.get(
                    "resulting_post_state_key",
                    f"program:{recipe.furnace_program_key}",
                ),
                "effective_date": recipe.effective_date,
                "expiry_date": recipe.expiry_date,
                "active": recipe.active,
                "source": MIGRATION_SOURCE,
            },
        )
        Recipe.objects.using(database).filter(pk=recipe.pk).update(
            furnace_program_id=identifier
        )
    for load in FurnaceLoad.objects.using(database).exclude(recipe_id__isnull=True):
        program_id = (
            Recipe.objects.using(database)
            .filter(pk=load.recipe_id)
            .values_list("furnace_program_id", flat=True)
            .first()
        )
        if program_id:
            FurnaceLoad.objects.using(database).filter(pk=load.pk).update(
                furnace_program_id=program_id
            )


def unlink_legacy_programs(apps, schema_editor):
    Program = apps.get_model("mlcc", "MlccFurnaceProgram")
    Recipe = apps.get_model("mlcc", "MlccRecipe")
    FurnaceLoad = apps.get_model("mlcc", "MlccFurnaceLoad")
    database = schema_editor.connection.alias
    FurnaceLoad.objects.using(database).update(furnace_program_id=None)
    Recipe.objects.using(database).update(furnace_program_id=None)
    Program.objects.using(database).filter(source=MIGRATION_SOURCE).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("input", "0084_parameter_plan_solver"),
        ("mlcc", "0006_furnace_load_attributes"),
    ]

    operations = [
        migrations.CreateModel(
            name="MlccFurnaceProgram",
            fields=[
                (
                    "source",
                    models.CharField(
                        blank=True, db_index=True, null=True, verbose_name="source"
                    ),
                ),
                (
                    "lastmodified",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="last modified",
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        max_length=200,
                        primary_key=True,
                        serialize=False,
                        verbose_name="stable business identifier",
                    ),
                ),
                (
                    "program_key",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        verbose_name="furnace program key",
                    ),
                ),
                ("version", models.CharField(max_length=40, verbose_name="version")),
                (
                    "process_stage",
                    models.CharField(
                        choices=[
                            ("stacking", "stacking"),
                            ("lamination", "lamination"),
                            ("cutting", "cutting"),
                            ("debinding", "debinding"),
                            ("sintering", "sintering"),
                        ],
                        max_length=30,
                        verbose_name="process stage",
                    ),
                ),
                (
                    "atmosphere_key",
                    models.CharField(max_length=100, verbose_name="atmosphere key"),
                ),
                (
                    "required_pre_state_key",
                    models.CharField(
                        max_length=100, verbose_name="required pre-state key"
                    ),
                ),
                (
                    "resulting_post_state_key",
                    models.CharField(
                        max_length=100, verbose_name="resulting post-state key"
                    ),
                ),
                ("effective_date", models.DateField(verbose_name="effective date")),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="expiry date"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "MLCC furnace program",
                "verbose_name_plural": "MLCC furnace programs",
                "db_table": "mlcc_furnace_program",
                "ordering": ("process_stage", "program_key", "version"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MlccFurnaceTransitionRule",
            fields=[
                (
                    "source",
                    models.CharField(
                        blank=True, db_index=True, null=True, verbose_name="source"
                    ),
                ),
                (
                    "lastmodified",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="last modified",
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="identifier"
                    ),
                ),
                (
                    "equipment_group",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="equipment group",
                    ),
                ),
                (
                    "process_stage",
                    models.CharField(
                        choices=[
                            ("stacking", "stacking"),
                            ("lamination", "lamination"),
                            ("cutting", "cutting"),
                            ("debinding", "debinding"),
                            ("sintering", "sintering"),
                        ],
                        max_length=30,
                        verbose_name="process stage",
                    ),
                ),
                (
                    "from_state_key",
                    models.CharField(max_length=100, verbose_name="from state key"),
                ),
                (
                    "transition_type",
                    models.CharField(
                        choices=[
                            ("none", "none"),
                            ("cleaning", "cleaning"),
                            ("atmosphere_purge", "atmosphere purge"),
                            ("empty_run", "empty run"),
                            ("heating", "heating"),
                            ("cooling", "cooling"),
                            ("composite", "composite"),
                        ],
                        default="none",
                        max_length=30,
                        verbose_name="transition type",
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        default=datetime.timedelta(0), verbose_name="duration"
                    ),
                ),
                (
                    "setup_cost",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="setup cost",
                    ),
                ),
                ("allowed", models.BooleanField(default=True, verbose_name="allowed")),
                ("enabled", models.BooleanField(default=True, verbose_name="enabled")),
                ("priority", models.IntegerField(default=0, verbose_name="priority")),
                ("effective_date", models.DateField(verbose_name="effective date")),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="expiry date"),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mlcc_furnace_transition_rules",
                        to="input.resource",
                        verbose_name="resource",
                    ),
                ),
                (
                    "to_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transition_rules",
                        to="mlcc.mlccfurnaceprogram",
                        verbose_name="target furnace program",
                    ),
                ),
            ],
            options={
                "verbose_name": "MLCC furnace transition rule",
                "verbose_name_plural": "MLCC furnace transition rules",
                "db_table": "mlcc_furnace_transition_rule",
                "ordering": (
                    "process_stage",
                    "resource",
                    "equipment_group",
                    "from_state_key",
                    "to_program",
                    "priority",
                    "id",
                ),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MlccFurnaceTransition",
            fields=[
                (
                    "source",
                    models.CharField(
                        blank=True, db_index=True, null=True, verbose_name="source"
                    ),
                ),
                (
                    "lastmodified",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="last modified",
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="identifier"
                    ),
                ),
                (
                    "transition_type",
                    models.CharField(
                        choices=[
                            ("none", "none"),
                            ("cleaning", "cleaning"),
                            ("atmosphere_purge", "atmosphere purge"),
                            ("empty_run", "empty run"),
                            ("heating", "heating"),
                            ("cooling", "cooling"),
                            ("composite", "composite"),
                        ],
                        max_length=30,
                        verbose_name="transition type",
                    ),
                ),
                ("planned_start", models.DateTimeField(verbose_name="planned start")),
                ("planned_end", models.DateTimeField(verbose_name="planned end")),
                (
                    "status",
                    models.CharField(
                        choices=[("proposed", "proposed")],
                        default="proposed",
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="details"),
                ),
                (
                    "predecessor_load",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_transitions",
                        to="mlcc.mlccfurnaceload",
                        verbose_name="predecessor furnace load",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mlcc_furnace_transitions",
                        to="input.resource",
                        verbose_name="resource",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="furnace_transitions",
                        to="mlcc.mlccschedulerun",
                        verbose_name="schedule run",
                    ),
                ),
                (
                    "successor_load",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transitions",
                        to="mlcc.mlccfurnaceload",
                        verbose_name="successor furnace load",
                    ),
                ),
                (
                    "transition_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planned_transitions",
                        to="mlcc.mlccfurnacetransitionrule",
                        verbose_name="transition rule",
                    ),
                ),
            ],
            options={
                "verbose_name": "MLCC furnace transition",
                "verbose_name_plural": "MLCC furnace transitions",
                "db_table": "mlcc_furnace_transition",
                "ordering": ("resource", "planned_start", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MlccFurnaceStateSnapshot",
            fields=[
                (
                    "source",
                    models.CharField(
                        blank=True, db_index=True, null=True, verbose_name="source"
                    ),
                ),
                (
                    "lastmodified",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="last modified",
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="identifier"
                    ),
                ),
                (
                    "observed_at",
                    models.DateTimeField(db_index=True, verbose_name="observed at"),
                ),
                (
                    "state_key",
                    models.CharField(max_length=100, verbose_name="state key"),
                ),
                ("available_at", models.DateTimeField(verbose_name="available at")),
                (
                    "current_program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="state_snapshots",
                        to="mlcc.mlccfurnaceprogram",
                        verbose_name="current furnace program",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mlcc_furnace_state_snapshots",
                        to="input.resource",
                        verbose_name="resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "MLCC furnace state snapshot",
                "verbose_name_plural": "MLCC furnace state snapshots",
                "db_table": "mlcc_furnace_state_snapshot",
                "ordering": ("resource", "-observed_at", "id"),
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="mlccfurnaceprogram",
            constraint=models.UniqueConstraint(
                fields=("program_key", "version"),
                name="mlcc_furnace_program_key_version_uniq",
            ),
        ),
        migrations.AddField(
            model_name="mlccfurnaceload",
            name="furnace_program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="furnace_loads",
                to="mlcc.mlccfurnaceprogram",
                verbose_name="furnace program",
            ),
        ),
        migrations.AddField(
            model_name="mlccrecipe",
            name="furnace_program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recipes",
                to="mlcc.mlccfurnaceprogram",
                verbose_name="furnace program",
            ),
        ),
        migrations.RunPython(link_legacy_programs, unlink_legacy_programs),
        migrations.AddConstraint(
            model_name="mlccfurnacetransitionrule",
            constraint=models.CheckConstraint(
                check=models.Q(("duration__gte", datetime.timedelta(0))),
                name="mlcc_transition_rule_duration_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="mlccfurnacetransitionrule",
            constraint=models.CheckConstraint(
                check=models.Q(("setup_cost__gte", 0)),
                name="mlcc_transition_rule_cost_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="mlccfurnacetransitionrule",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("resource__isnull", False),
                    ("equipment_group__isnull", False),
                    _negated=True,
                ),
                name="mlcc_transition_rule_single_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="mlccfurnacetransition",
            constraint=models.UniqueConstraint(
                fields=("run", "successor_load"),
                name="mlcc_furnace_transition_successor_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="mlccfurnacetransition",
            constraint=models.CheckConstraint(
                check=models.Q(("status", "proposed")),
                name="mlcc_furnace_transition_proposed",
            ),
        ),
        migrations.AddConstraint(
            model_name="mlccfurnacestatesnapshot",
            constraint=models.UniqueConstraint(
                fields=("resource", "observed_at"),
                name="mlcc_furnace_state_resource_time_uniq",
            ),
        ),
    ]
